version: '3.9'
services:

  init:
    depends_on:
      - pg-server
    build:
      dockerfile: init.Dockerfile
      context: .
    env_file:
      - .env
  migrate:
    depends_on:
      - pg-server
    build:
      dockerfile: migrations.Dockerfile
      context: .
    env_file:
      - .env
  api:
    depends_on:
      - migrate
    build:
      dockerfile: tradealpha/api/Dockerfile
      context: .
    ports:
      - "5000:5000"
    env_file:
      - .env
  collector:
    depends_on:
      - migrate
    build:
      dockerfile: tradealpha/collector/Dockerfile
      context: .
    env_file:
      - .env
  bot:
    depends_on:
      - migrate
    build:
      dockerfile: tradealpha/bot/Dockerfile
      context: .
    env_file:
      - .env
  redis:
    image: "redis:latest"
    container_name: redis-server
    ports:
      - "6379:6379"
  pg-server:
    image: "postgres"
    container_name: pg-server
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=postgres"

volumes:
  pg-data:
