version: '3.9'
services:
  migrate:
    depends_on:
      - pg-server
    build:
      dockerfile: migrations.Dockerfile
      context: .
    env_file:
      - .env
  api:
    depends_on:
      - migrate
      - redis-server
    build:
      dockerfile: projects/api/Dockerfile
      context: .
    ports:
      - "5000:5000"
    env_file:
      - .env
  collector:
    depends_on:
      - migrate
      - redis-server
    build:
      dockerfile: projects/collector/Dockerfile
      context: .
    env_file:
      - .env
  bot:
    depends_on:
      - migrate
      - redis-server
    build:
      dockerfile: projects/bot/Dockerfile
      context: .
    env_file:
      - .env
  web:
    image: "nginx:latest"
    volumes:
      - ./nginx.confg:/etc/nginx/nginx.confg
    ports:
      - "80:80"
      - "443:443"
  redis-server:
    image: "redis:latest"
    container_name: redis-server
    ports:
      - "6379:6379"
    env_file:
      - .env
  pg-server:
    image: "postgres"
    container_name: pg-server
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_DB=postgres"
    env_file:
      - .env

volumes:
  pg-data:
