"""add info and about_me cols to user

Revision ID: 0b86b2e9d925
Revises: 358424d1dd1c
Create Date: 2022-10-28 22:28:18.815633

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy import update
from sqlalchemy.orm import Session

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
from database.dbmodels.user import OAuthAccount

revision = '0b86b2e9d925'
down_revision = '358424d1dd1c'
branch_labels = None
depends_on = None


def upgrade():
    session = Session(bind=op.get_bind())
    session.execute(
        update(OAuthAccount).values(
            data=None
        )
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfer', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('transfer_id_seq'::regclass)"))
    op.add_column('user', sa.Column('info', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'info')
    op.alter_column('transfer', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True,
               existing_server_default=sa.text("nextval('transfer_id_seq'::regclass)"))
    # ### end Alembic commands ###
