"""make init balance not null

Revision ID: 150590cb8130
Revises: 0a3782ac454d
Create Date: 2022-10-09 16:00:48.188210

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy import delete, update
from sqlalchemy.orm import Session

# revision identifiers, used by Alembic.
from database.dbmodels import Client
from database.dbmodels.trade import Trade

revision = '150590cb8130'
down_revision = '0a3782ac454d'
branch_labels = None
depends_on = None


def upgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    session.execute(
        delete(Trade)
    )
    session.execute(
        update(Client).values(
            last_transfer_sync=None,
            last_execution_sync=None
        )
    )
    session.commit()
    op.alter_column('trade', 'init_balance_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade', 'init_balance_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
