"""make init balance not null

Revision ID: 150590cb8130
Revises: 0a3782ac454d
Create Date: 2022-10-09 16:00:48.188210

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '150590cb8130'
down_revision = '0a3782ac454d'
branch_labels = None
depends_on = None


def upgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade', 'init_balance_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade', 'init_balance_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
