"""fix typo

Revision ID: 1f35497b5996
Revises: 21a8724671d8
Create Date: 2022-09-29 15:47:05.466083

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = '1f35497b5996'
down_revision = '21a8724671d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', column_name='rekt_treshhold', new_column_name='rekt_threshold')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', new_column_name='rekt_treshhold', column_name='rekt_threshold')
    # ### end Alembic commands ###
