"""add market type to exec

Revision ID: 3e73e9ecc90e
Revises: 5f9dd601983a
Create Date: 2022-12-13 19:42:59.460904

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3e73e9ecc90e'
down_revision = '5f9dd601983a'
branch_labels = None
depends_on = None

enum = sa.Enum('SPOT', 'DERIVATIVES', name='markettype')

def upgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    enum.create(bind=op.get_bind())
    op.add_column('execution', sa.Column('market_type', enum, nullable=False, server_default='DERIVATIVES'))
    # ### end Alembic commands ###


def downgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execution', 'market_type')
    enum.drop(bind=op.get_bind())
    # ### end Alembic commands ###
