"""add transfer_id to exec

Revision ID: 4baacbf738d6
Revises: e845d16188d5
Create Date: 2022-10-24 21:15:15.200837

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session

from sqlalchemy.dialects import postgresql
from database.dbmodels import Client, Balance, Execution
from database.dbmodels.trade import Trade
from database.dbmodels.transfer import Transfer
from sqlalchemy import update, delete
from sqlalchemy.orm import Session


# revision identifiers, used by Alembic.
revision = '4baacbf738d6'
down_revision = 'e845d16188d5'
branch_labels = None
depends_on = None


def upgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    session.execute(
        update(Client).values(
            last_execution_sync=None,
            last_transfer_sync=None
        )
    )
    session.execute(
        delete(Trade)
    )
    session.execute(
        delete(Balance)
    )
    session.execute(
        delete(Transfer)
    )
    op.add_column('execution', sa.Column('transfer_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'execution', ['trade_id', 'transfer_id'])
    op.create_foreign_key(None, 'execution', 'transfer', ['transfer_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'execution', type_='foreignkey')
    op.drop_constraint(None, 'execution', type_='unique')
    op.drop_column('execution', 'transfer_id')
    # ### end Alembic commands ###
