"""fix foreign key on chaptergrant

Revision ID: 6953e25d67fe
Revises: 76728ce5b2dc
Create Date: 2022-11-04 23:54:27.992092

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6953e25d67fe'
down_revision = '76728ce5b2dc'
branch_labels = None
depends_on = None


def upgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_id_fkey', 'chaptergrant', type_='foreignkey')
    op.create_foreign_key('chapter_id_fkey', 'chaptergrant', 'chapter', ['chapter_id'], ['id'], ondelete='CASCADE')
    op.alter_column('journal', 'chapter_interval',
               existing_type=postgresql.INTERVAL(),
               type_=sa.Enum('DAY', 'WEEK', 'MONTH', name='intervaltype'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('journal', 'chapter_interval',
               existing_type=sa.Enum('DAY', 'WEEK', 'MONTH', name='intervaltype'),
               type_=postgresql.INTERVAL(),
               existing_nullable=True)
    op.drop_constraint('chapter_id_fkey', 'chaptergrant', type_='foreignkey')
    op.create_foreign_key('event_id_fkey', 'chaptergrant', 'event', ['chapter_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
