"""add wildcards to authgrant

Revision ID: 76728ce5b2dc
Revises: ef56206a626e
Create Date: 2022-11-04 22:01:32.873868

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
from database.dbmodels.authgrant import AssociationType

revision = '76728ce5b2dc'
down_revision = 'ef56206a626e'
branch_labels = None
depends_on = None


def upgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(AssociationType).create(bind=op.get_bind())
    op.add_column('authgrant', sa.Column('wildcards', sa.ARRAY(sa.Enum('EVENT', 'CHAPTER', 'TRADE', 'JOURNAL', name='granttype')), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum(AssociationType).drop(op.get_bind())
    op.drop_column('authgrant', 'wildcards')
    # ### end Alembic commands ###
