"""redo evententry and score schemas

Revision ID: 8c304830d9af
Revises: 0b86b2e9d925
Create Date: 2022-10-28 23:34:29.862483

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy import delete
from sqlalchemy.orm import Session

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
from database.dbmodels import EventEntry

revision = '8c304830d9af'
down_revision = '0b86b2e9d925'
branch_labels = None
depends_on = None


def upgrade():
    session = Session(bind=op.get_bind())
    session.execute(
        delete(EventEntry)
    )
    session.commit()
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('evententry_client_id_fkey', 'evententry', type_='foreignkey')
    op.drop_constraint('eventscore_client_id_fkey', 'eventscore', type_='foreignkey')
    op.drop_constraint('eventscore_event_id_fkey', 'eventscore', type_='foreignkey')
    op.drop_constraint('evententry_pkey', 'evententry', type_='primary')
    op.drop_column('eventscore', 'client_id')
    op.drop_column('eventscore', 'event_id')
    op.add_column('eventscore', sa.Column('entry_id', sa.Integer(), nullable=False, primary_key=True))
    op.add_column('evententry', sa.Column('id', sa.Integer(), nullable=False, primary_key=True, unique=True))
    op.add_column('evententry', sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False))
    op.create_foreign_key('evententry_client_id_fkey', 'evententry', 'client', ['client_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('evententry_user_id_fkey', 'evententry', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('eventscore_entry_id_fkey', 'eventscore', 'evententry', ['entry_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('eventscore', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('eventscore', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'eventscore', type_='foreignkey')
    op.create_foreign_key('eventscore_event_id_fkey', 'eventscore', 'event', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('eventscore_client_id_fkey', 'eventscore', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_column('eventscore', 'entry_id')
    op.drop_constraint('evententry_user_id_fkey', 'evententry', type_='foreignkey')
    op.drop_constraint('evententry_client_id_fkey', 'evententry', type_='foreignkey')
    op.create_foreign_key('evententry_client_id_fkey', 'evententry', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    op.drop_column('evententry', 'user_id')
    op.drop_column('evententry', 'id')
    # ### end Alembic commands ###
