"""remove rekt_on from client and add final_summary to event

Revision ID: c75fd142c203
Revises: 5f2bdbbb4b16
Create Date: 2022-10-19 20:05:57.176428

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
from database.dbmodels.event import SummaryType

revision = 'c75fd142c203'
down_revision = '5f2bdbbb4b16'
branch_labels = None
depends_on = None


def upgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'rekt_on')
    op.add_column('event', sa.Column('final_summary', SummaryType, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'final_summary')
    op.add_column('client', sa.Column('rekt_on', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
