"""make currency varchar

Revision ID: cd3ea0fe29c6
Revises: a56e49577f73
Create Date: 2022-11-11 23:45:11.321448

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd3ea0fe29c6'
down_revision = 'a56e49577f73'
branch_labels = None
depends_on = None


def upgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('amount', 'currency', type=sa.VARCHAR)
    # ### end Alembic commands ###


def downgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
