"""remove unnecessary transfer cols

Revision ID: e845d16188d5
Revises: 439d8fa64429
Create Date: 2022-10-22 15:21:51.946254

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy import update, delete
from sqlalchemy.orm import Session

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
from database.dbmodels import Client, Balance, Execution
from database.dbmodels.trade import Trade
from database.dbmodels.transfer import Transfer

revision = 'e845d16188d5'
down_revision = '439d8fa64429'
branch_labels = None
depends_on = None


def upgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    session.execute(
        update(Client).values(
            last_execution_sync=None,
            last_transfer_sync=None
        )
    )
    session.execute(
        delete(Trade)
    )
    session.execute(
        delete(Balance)
    )
    session.execute(
        delete(Transfer)
    )
    session.commit()
    op.alter_column('transfer', 'execution_id',
                    existing_type=sa.INTEGER(),
                    nullable=False)
    op.drop_index('ix_transfer_time', table_name='transfer')
    op.drop_column('transfer', 'commission')
    op.drop_column('transfer', 'coin')
    op.drop_column('transfer', 'time')
    op.drop_column('transfer', 'amount')
    op.drop_column('transfer', 'extra_currencies')
    # ### end Alembic commands ###


def downgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer',
                  sa.Column('extra_currencies', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False,
                            nullable=True))
    op.add_column('transfer', sa.Column('amount', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.add_column('transfer',
                  sa.Column('time', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('transfer', sa.Column('coin', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('transfer', sa.Column('commission', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.create_index('ix_transfer_time', 'transfer', ['time'], unique=False)
    op.alter_column('transfer', 'execution_id',
                    existing_type=sa.INTEGER(),
                    nullable=True)
    # ### end Alembic commands ###
