"""rename bybit

Revision ID: eee37086c3b9
Revises: d114ff70a3af
Create Date: 2022-12-01 20:19:16.022285

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy import update
from sqlalchemy.orm import Session

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
from database.dbmodels import Client

revision = 'eee37086c3b9'
down_revision = 'd114ff70a3af'
branch_labels = None
depends_on = None


def upgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    session.execute(
        update(Client).values(
            exchange='bybit-derivatives'
        ).where(
            Client.exchange.in_(('bybit-linear', 'bybit-inverse'))
        )
    )
    session.commit()
    # ### end Alembic commands ###


def downgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
