"""add unique constraint to event entry

Revision ID: f4263b42cb51
Revises: 8c304830d9af
Create Date: 2022-10-29 00:08:52.277347

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4263b42cb51'
down_revision = '8c304830d9af'
branch_labels = None
depends_on = None


def upgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('evententry', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_unique_constraint('evententry_user_id_event_id_key', 'evententry', ['user_id', 'event_id'])
    # ### end Alembic commands ###


def downgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('evententry_user_id_event_id_key', 'evententry', type_='unique')
    op.alter_column('evententry', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
