"""revisit action ddl

Revision ID: f6be99aae636
Revises: 02020a57ea5c
Create Date: 2022-11-25 15:56:55.123673

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
from database.dbmodels.types import Platform

revision = 'f6be99aae636'
down_revision = '02020a57ea5c'
branch_labels = None
depends_on = None


def upgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action', 'action_type')
    enum = sa.Enum('CLIENT', 'TRADE', 'JOURNAL', 'BALANCE', name='actiontype')
    enum.drop(bind=op.get_bind())
    enum.create(bind=op.get_bind())
    op.add_column('action', sa.Column('type', enum, nullable=False))
    op.add_column('action', sa.Column('platform', Platform, nullable=False))
    op.alter_column('action', 'trigger_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_column('action', 'extra')
    op.drop_column('action', 'namespace')
    # ### end Alembic commands ###


def downgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('action', sa.Column('namespace', sa.VARCHAR(length=12), autoincrement=False, nullable=False))
    op.add_column('action', sa.Column('action_type', postgresql.ENUM('WEBHOOK', 'DISCORD', name='actiontype'), autoincrement=False, nullable=False))
    op.add_column('action', sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.alter_column('action', 'trigger_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('action', 'platform')
    op.drop_column('action', 'type')
    # ### end Alembic commands ###
