"""add about_me to user

Revision ID: fa3c22038e23
Revises: a068507680cd
Create Date: 2022-10-29 14:18:40.196004

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
import database
from database.dbmodels.types import Document

revision = 'fa3c22038e23'
down_revision = 'a068507680cd'
branch_labels = None
depends_on = None


def upgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', Document, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
