"""lossen constraints on trade

Revision ID: 01187333c9f2
Revises: 665830fb7d4f
Create Date: 2022-09-04 19:05:52.590620

"""
from alembic import op
import sqlalchemy as sa
import tradealpha


# revision identifiers, used by Alembic.
revision = '01187333c9f2'
down_revision = '665830fb7d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade', 'max_pnl_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trade', 'min_pnl_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade', 'min_pnl_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trade', 'max_pnl_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
