"""add pnl table

Revision ID: 127bef4f183d
Revises: eeec27da77ac
Create Date: 2022-04-29 16:19:15.757203

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
from sqlalchemy.dialects.postgresql import JSONB

revision = '127bef4f183d'
down_revision = 'eeec27da77ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_column('balance', 'currency')
    op.add_column('client', sa.Column('currency', sa.String(length=10), nullable=True))
    op.add_column('client', sa.Column('last_transfer_sync', sa.DateTime(timezone=True), nullable=True))
    op.add_column('trade', sa.Column('max_pnl_id', sa.Integer(), nullable=True))
    op.add_column('trade', sa.Column('min_pnl_id', sa.Integer(), nullable=True))
    op.drop_constraint('trade_max_upnl_id_fkey', 'trade', type_='foreignkey')
    op.drop_constraint('trade_min_upnl_id_fkey', 'trade', type_='foreignkey')
    op.create_foreign_key(None, 'trade', 'pnldata', ['max_pnl_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'trade', 'pnldata', ['min_pnl_id'], ['id'], ondelete='SET NULL')
    op.drop_column('trade', 'max_upnl_id')
    op.drop_column('trade', 'min_upnl_id')
    op.add_column('transfer', sa.Column('client_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transfer', 'client', ['client_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfer', type_='foreignkey')
    op.drop_column('transfer', 'client_id')
    op.add_column('trade', sa.Column('min_upnl_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('trade', sa.Column('max_upnl_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'trade', type_='foreignkey')
    op.drop_constraint(None, 'trade', type_='foreignkey')
    op.create_foreign_key('trade_min_upnl_id_fkey', 'trade', 'balance', ['min_upnl_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('trade_max_upnl_id_fkey', 'trade', 'balance', ['max_upnl_id'], ['id'], ondelete='SET NULL')
    op.drop_column('trade', 'min_pnl_id')
    op.drop_column('trade', 'max_pnl_id')
    op.drop_column('client', 'last_transfer_sync')
    op.drop_column('client', 'currency')
    op.add_column('balance', sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('balance', 'extra_currencies',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.BYTEA(),
               existing_nullable=True)
    # ### end Alembic commands ###
