"""add title to chapter

Revision ID: 188a5325bac1
Revises: d03e280b54ba
Create Date: 2022-07-04 18:53:47.625853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '188a5325bac1'
down_revision = 'd03e280b54ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('title', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapter', 'title')
    # ### end Alembic commands ###
