"""add fee to transfer

Revision ID: 18b09e8ab0a2
Revises: f09c0b5bb30d
Create Date: 2022-06-07 18:37:23.240614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18b09e8ab0a2'
down_revision = 'f09c0b5bb30d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer', sa.Column('fee', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer', 'fee')
    # ### end Alembic commands ###
