"""add exec sync col to client

Revision ID: 2197236c87bb
Revises: cafb0a70bced
Create Date: 2022-05-14 21:46:50.057252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2197236c87bb'
down_revision = 'cafb0a70bced'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('last_execution_sync', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'last_execution_sync')
    # ### end Alembic commands ###
