"""add init_balance to event score

Revision ID: 22a897d6961f
Revises: 7636e2a2b265
Create Date: 2022-08-20 18:31:54.207443

"""
from alembic import op
import sqlalchemy as sa
import tradealpha


# revision identifiers, used by Alembic.
revision = '22a897d6961f'
down_revision = '7636e2a2b265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association')
    op.add_column('eventscore', sa.Column('init_balance_id', sa.Integer(), nullable=True))
    op.alter_column('eventscore', 'abs_value',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('eventscore', 'rel_value',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.drop_constraint('eventscore_event_id_fkey', 'eventscore', type_='foreignkey')
    op.drop_constraint('eventscore_client_id_fkey', 'eventscore', type_='foreignkey')
    op.create_foreign_key(None, 'eventscore', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'eventscore', 'event', ['event_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'eventscore', 'balance', ['init_balance_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'eventscore', type_='foreignkey')
    op.drop_constraint(None, 'eventscore', type_='foreignkey')
    op.drop_constraint(None, 'eventscore', type_='foreignkey')
    op.create_foreign_key('eventscore_client_id_fkey', 'eventscore', 'client', ['client_id'], ['id'])
    op.create_foreign_key('eventscore_event_id_fkey', 'eventscore', 'event', ['event_id'], ['id'])
    op.alter_column('eventscore', 'rel_value',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('eventscore', 'abs_value',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.drop_column('eventscore', 'init_balance_id')
    op.create_table('association',
    sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='association_client_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='association_event_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', 'client_id', name='association_pkey')
    )
    # ### end Alembic commands ###
