"""template adjustion

Revision ID: 26ad98d52e0c
Revises: 36f8258078ab
Create Date: 2022-07-26 20:46:40.992161

"""
from alembic import op
import sqlalchemy as sa
import tradealpha


# revision identifiers, used by Alembic.
revision = '26ad98d52e0c'
down_revision = '36f8258078ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template', sa.Column('data', tradealpha.common.dbmodels.types.ResultT(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('template', 'data')
    # ### end Alembic commands ###
