"""add trigger type to action

Revision ID: 2e2ccd52b7b1
Revises: 1f35497b5996
Create Date: 2022-09-30 21:28:05.263380

"""
from alembic import op
import sqlalchemy as sa
import tradealpha
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2e2ccd52b7b1'
down_revision = '1f35497b5996'
branch_labels = None
depends_on = None


e = postgresql.ENUM('ONCE', 'RECURRING', name='actiontrigger')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    e.create(op.get_bind())
    op.add_column('action', sa.Column('trigger_type', e, nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('action', 'trigger_type')
    e.drop(op.get_bind())
    # ### end Alembic commands ###
