"""cascade for template and journal

Revision ID: 31268f1f9942
Revises: 77577310b6d6
Create Date: 2022-08-09 17:05:25.950787

"""
from alembic import op
import sqlalchemy as sa
import tradealpha


# revision identifiers, used by Alembic.
revision = '31268f1f9942'
down_revision = '77577310b6d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('journal_user_id_fkey', 'journal', type_='foreignkey')
    op.create_foreign_key(None, 'journal', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('template_user_id_fkey', 'template', type_='foreignkey')
    op.create_foreign_key(None, 'template', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'template', type_='foreignkey')
    op.create_foreign_key('template_user_id_fkey', 'template', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'journal', type_='foreignkey')
    op.create_foreign_key('journal_user_id_fkey', 'journal', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
