"""remove non null on guild assoc for client

Revision ID: 3227580df717
Revises: 
Create Date: 2022-06-24 12:35:34.166924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3227580df717'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('guild_association_pkey', 'guild_association')
    op.create_primary_key('guild_association_pkey', 'guild_association', ['guild_id', 'discord_user_id'])
    op.alter_column('guild_association', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guild_association', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('guild_association', 'client_id',
               existing_type=sa.INTEGER(),
               primary_key=True)
    # ### end Alembic commands ###
