"""journal default template key ondelete

Revision ID: 36f8258078ab
Revises: ebfe0ff27301
Create Date: 2022-07-16 14:39:22.388801

"""
from alembic import op
import sqlalchemy as sa
import tradealpha


# revision identifiers, used by Alembic.
revision = '36f8258078ab'
down_revision = 'ebfe0ff27301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('journal_default_template_id_fkey', 'journal', type_='foreignkey')
    op.create_foreign_key('journal_default_template_id_fkey', 'journal', 'template', ['default_template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('journal_default_template_id_fkey', 'journal', type_='foreignkey')
    op.create_foreign_key('journal_default_template_id_fkey', 'journal', 'template', ['default_template_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
