"""migrate chpater interval

Revision ID: 39779de1e471
Revises: bf0c03abe6f9
Create Date: 2022-09-09 14:47:40.685120

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import tradealpha


# revision identifiers, used by Alembic.
revision = '39779de1e471'
down_revision = 'bf0c03abe6f9'
branch_labels = None
depends_on = None

en = postgresql.ENUM('DAY', 'WEEK', 'MONTH', name='intervaltype')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    en.create(op.get_bind())
    op.add_column('journal', sa.Column('chapter_interval', en, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal', 'chapter_interval')
    en.drop(op.get_bind())
    # ### end Alembic commands ###
