"""add data to chapter, migrate types

Revision ID: 3b5bb49d8a65
Revises: 49d41f5e8913
Create Date: 2022-07-11 18:48:30.580312

"""
from alembic import op
import sqlalchemy as sa
import tradealpha

# revision identifiers, used by Alembic.
revision = '3b5bb49d8a65'
down_revision = '49d41f5e8913'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.add_column('chapter',
                  sa.Column('data', tradealpha.common.dbmodels.chapter.Data(astext_type=sa.Text()), nullable=True))
    op.drop_column('chapter', 'notes')
    op.add_column('chapter', sa.Column('notes', tradealpha.common.dbmodels.chapter.Document(astext_type=sa.Text())))
    op.create_foreign_key(None, 'chapter', 'chapter', ['parent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapter', type_='foreignkey')
    op.alter_column('chapter', 'notes',
                    existing_type=tradealpha.common.dbmodels.chapter.Document(astext_type=sa.Text()),
                    type_=sa.TEXT(),
                    existing_nullable=True)
    op.drop_column('chapter', 'data')
    op.drop_column('chapter', 'parent_id')
    # ### end Alembic commands ###
