"""revisit extra currencies

Revision ID: 3c38d785407b
Revises: 79f5a5cac328
Create Date: 2022-09-01 00:43:02.252880

"""
from alembic import op
import sqlalchemy as sa
import tradealpha
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3c38d785407b'
down_revision = '79f5a5cac328'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amount',
    sa.Column('realized', sa.Numeric(), nullable=False),
    sa.Column('unrealized', sa.Numeric(), nullable=False),
    sa.Column('balance_id', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.ForeignKeyConstraint(['balance_id'], ['balance.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('balance_id', 'currency')
    )
    op.drop_column('balance', 'extra_currencies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance', sa.Column('extra_currencies', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_table('amount')
    # ### end Alembic commands ###
