"""discord migration

Revision ID: 3dfc3b839d8c
Revises: e35c088672d2
Create Date: 2022-08-24 17:07:34.904271

"""
import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa
import tradealpha
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3dfc3b839d8c'
down_revision = 'e35c088672d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_account',
                    sa.Column('oauth_name', sa.String(length=100), nullable=False),
                    sa.Column('access_token', sa.String(length=1024), nullable=False),
                    sa.Column('expires_at', sa.Integer(), nullable=True),
                    sa.Column('refresh_token', sa.String(length=1024), nullable=True),
                    sa.Column('account_email', sa.String(length=320), nullable=False),
                    sa.Column('id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
                    sa.Column('account_id', sa.String(length=320), nullable=False),
                    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_index(op.f('ix_oauth_account_account_id'), 'oauth_account', ['account_id'], unique=True)
    op.create_index(op.f('ix_oauth_account_oauth_name'), 'oauth_account', ['oauth_name'], unique=False)

    op.drop_constraint('alert_discord_user_id_fkey', 'alert', type_='foreignkey')
    op.alter_column('alert', 'discord_user_id',
                    existing_type=sa.BIGINT(),
                    type_=sa.String(length=320),
                    existing_nullable=True)
    op.create_foreign_key(None, 'alert', 'oauth_account', ['discord_user_id'], ['account_id'], ondelete='SET NULL')

    op.add_column('client', sa.Column('oauth_account_id', sa.String(length=320), nullable=True))
    op.drop_constraint('client_discord_user_id_fkey', 'client', type_='foreignkey')
    op.create_foreign_key(None, 'client', 'oauth_account', ['oauth_account_id'], ['account_id'], ondelete='SET NULL')
    op.drop_column('client', 'discord_user_id')
    op.alter_column('event', 'description',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    nullable=False)

    op.drop_constraint('guild_association_discord_user_id_fkey', 'guild_association', type_='foreignkey')
    op.alter_column('guild_association', 'discord_user_id',
                    existing_type=sa.BIGINT(),
                    type_=sa.String(length=320),
                    existing_nullable=True)
    op.create_foreign_key(None, 'guild_association', 'oauth_account', ['discord_user_id'], ['account_id'],
                          ondelete='CASCADE')
    op.drop_constraint('user_discord_user_id_fkey', 'user', type_='foreignkey')
    op.drop_column('user', 'discord_user_id')
    op.drop_table('discorduser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discorduser',
                    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
                    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.Column('avatar', sa.VARCHAR(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('id', name='discorduser_pkey')
                    )
    op.drop_index(op.f('ix_oauth_account_oauth_name'), table_name='oauth_account')
    op.drop_index(op.f('ix_oauth_account_account_id'), table_name='oauth_account')
    op.add_column('user', sa.Column('discord_user_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.create_foreign_key('user_discord_user_id_fkey', 'user', 'discorduser', ['discord_user_id'], ['id'],
                          ondelete='SET NULL')
    op.drop_constraint(None, 'guild_association', type_='foreignkey')
    op.create_foreign_key('guild_association_discord_user_id_fkey', 'guild_association', 'discorduser',
                          ['discord_user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('event', 'description',
                    existing_type=postgresql.JSONB(astext_type=sa.Text()),
                    nullable=True)
    op.add_column('client', sa.Column('discord_user_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.create_foreign_key('client_discord_user_id_fkey', 'client', 'discorduser', ['discord_user_id'], ['id'],
                          ondelete='CASCADE')
    op.drop_column('client', 'oauth_account_id')
    op.drop_constraint(None, 'alert', type_='foreignkey')
    op.create_foreign_key('alert_discord_user_id_fkey', 'alert', 'discorduser', ['discord_user_id'], ['id'],
                          ondelete='SET NULL')
    op.alter_column('alert', 'discord_user_id',
                    existing_type=sa.String(length=320),
                    type_=sa.BIGINT(),
                    existing_nullable=True)

    op.drop_table('oauth_account')
    # ### end Alembic commands ###
