"""rename notes to content

Revision ID: 44c089be861c
Revises: f784a913492c
Create Date: 2022-07-15 20:44:39.846786

"""
from alembic import op
import sqlalchemy as sa
import tradealpha
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '44c089be861c'
down_revision = 'f784a913492c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chapter', 'title')
    op.alter_column('chapter', column_name='notes', new_column_name='content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('title', sa.VARCHAR(length=25), autoincrement=False, nullable=True))
    op.alter_column('chapter', new_column_name='notes', column_name='content')

    # ### end Alembic commands ###
