"""execution options

Revision ID: 463e377fd137
Revises: 3c38d785407b
Create Date: 2022-09-04 18:18:59.463196

"""
from alembic import op
import sqlalchemy as sa
import tradealpha
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '463e377fd137'
down_revision = '3c38d785407b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute(f"ALTER TYPE exectype ADD VALUE 'VALUE'")
    op.execute(f"ALTER TYPE exectype ADD VALUE 'MISC'")

    op.alter_column('execution', 'type',
               existing_type=postgresql.ENUM('TRADE', 'STOP', 'TP', 'TRANSFER', name='exectype'),
               nullable=False)
    op.alter_column('execution', 'price',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('execution', 'qty',
               existing_type=sa.NUMERIC(),
               nullable=True)
    op.alter_column('execution', 'side',
               existing_type=postgresql.ENUM('BUY', 'SELL', name='side'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('execution', 'side',
               existing_type=postgresql.ENUM('BUY', 'SELL', name='side'),
               nullable=False)
    op.alter_column('execution', 'qty',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('execution', 'price',
               existing_type=sa.NUMERIC(),
               nullable=False)
    op.alter_column('execution', 'type',
               existing_type=postgresql.ENUM('TRADE', 'STOP', 'TP', 'TRANSFER', name='exectype'),
               nullable=True)
    # ### end Alembic commands ###
