"""init

Revision ID: 47d3c2c4fad6
Revises: 
Create Date: 2022-06-23 13:28:04.171457

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47d3c2c4fad6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guild_association', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('guild_association', 'client_id',
               existing_type=sa.INTEGER(),
               primary_key=False)
    op.add_column('trade', sa.Column('init_balance_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'trade', 'balance', ['init_balance_id'], ['id'], ondelete='SET NULL')
    op.add_column('transfer', sa.Column('commission', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer', 'commission')
    op.drop_constraint(None, 'trade', type_='foreignkey')
    op.drop_column('trade', 'init_balance_id')
    op.alter_column('guild_association', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
