"""add overview to jounral

Revision ID: 49d41f5e8913
Revises: e22aec034d40
Create Date: 2022-07-05 19:12:12.103151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49d41f5e8913'
down_revision = 'e22aec034d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal', sa.Column('overview', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal', 'overview')
    # ### end Alembic commands ###
