"""lossen constraints on trade

Revision ID: 51a41a3b280a
Revises: 87bb80bdb64f
Create Date: 2022-09-04 19:49:58.332444

"""
from alembic import op
import sqlalchemy as sa
import tradealpha


# revision identifiers, used by Alembic.
revision = '51a41a3b280a'
down_revision = '87bb80bdb64f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade', 'init_balance_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade', 'init_balance_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
