"""rename symbol col on transfer to coin

Revision ID: 559b4d802b81
Revises: ad402e99dea8
Create Date: 2022-05-15 21:10:40.048204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '559b4d802b81'
down_revision = 'ad402e99dea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer', sa.Column('coin', sa.String(), nullable=True))
    op.drop_column('transfer', 'symbol')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer', sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('transfer', 'coin')
    # ### end Alembic commands ###
