"""add owner to events

Revision ID: 5bfb9e506ab1
Revises: 5e9b868b7ad2
Create Date: 2022-08-19 20:34:01.634951

"""
import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa
import tradealpha


# revision identifiers, used by Alembic.
revision = '5bfb9e506ab1'
down_revision = '5e9b868b7ad2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('owner_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False))
    op.create_foreign_key(None, 'event', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.drop_column('event', 'owner_id')
    # ### end Alembic commands ###
