"""new events

Revision ID: 5e9b868b7ad2
Revises: a7ce3bd7db00
Create Date: 2022-08-19 18:05:46.416298

"""
from alembic import op
import sqlalchemy as sa
import tradealpha
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5e9b868b7ad2'
down_revision = 'a7ce3bd7db00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventscore',
    sa.Column('abs_value', sa.Numeric(), nullable=False),
    sa.Column('rel_value', sa.Numeric(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], )
    )
    op.add_column('event', sa.Column('max_registrations', sa.Integer(), nullable=False))
    op.add_column('event', sa.Column('public', sa.Boolean(), nullable=False))
    op.add_column('event', sa.Column('location', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    op.drop_constraint('event_guild_id_fkey', 'event', type_='foreignkey')
    op.drop_column('event', 'guild_id')
    op.drop_column('event', 'channel_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('channel_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('event', sa.Column('guild_id', sa.BIGINT(), autoincrement=False, nullable=False))
    op.create_foreign_key('event_guild_id_fkey', 'event', 'guild', ['guild_id'], ['id'], ondelete='CASCADE')
    op.drop_column('event', 'location')
    op.drop_column('event', 'public')
    op.drop_column('event', 'max_registrations')
    op.drop_table('eventscore')
    # ### end Alembic commands ###
