"""remove client_id from chapter

Revision ID: 5ef7b6e93e52
Revises: 81ab644f4596
Create Date: 2022-05-28 23:33:23.367462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef7b6e93e52'
down_revision = '81ab644f4596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chapter_client_id_fkey', 'chapter', type_='foreignkey')
    op.drop_column('chapter', 'client_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('chapter_client_id_fkey', 'chapter', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###
