"""data col on oauth

Revision ID: 665830fb7d4f
Revises: 8ff5d4ba6008
Create Date: 2022-09-04 18:50:48.286085

"""
from alembic import op
import sqlalchemy as sa
import tradealpha
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '665830fb7d4f'
down_revision = '8ff5d4ba6008'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('oauth_account', sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('oauth_account', 'data')
    # ### end Alembic commands ###
