"""add  currencies to transfer

Revision ID: 6702ad72532d
Revises: d82f0fadb2dc
Create Date: 2022-05-03 13:18:19.702758

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6702ad72532d'
down_revision = 'd82f0fadb2dc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfer', sa.Column('time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('transfer', sa.Column('extra_currencies', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('transfer', 'amount',
               existing_type=sa.NUMERIC(),
               type_=sa.Float(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfer', 'amount',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(),
               existing_nullable=False)
    op.drop_column('transfer', 'extra_currencies')
    op.drop_column('transfer', 'time')
    # ### end Alembic commands ###
