"""fix typo on trade table

Revision ID: 681682d5a72c
Revises: 95727bb7bd57
Create Date: 2022-05-27 11:34:52.600410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '681682d5a72c'
down_revision = '95727bb7bd57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade', sa.Column('total_commissions', sa.Numeric(), nullable=True))
    op.drop_column('trade', 'total_commisions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade', sa.Column('total_commisions', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('trade', 'total_commissions')
    # ### end Alembic commands ###
