"""migrate chpater interval

Revision ID: 6f7d06d8ab2f
Revises: a82b277b06e3
Create Date: 2022-09-09 13:50:59.638433

"""
from alembic import op
import sqlalchemy as sa
import tradealpha
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6f7d06d8ab2f'
down_revision = 'a82b277b06e3'
branch_labels = None
depends_on = None

en = sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='intervaltype')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    en.create(bind=op.get_bind())
    op.drop_column('journal', 'chapter_interval'),
    op.add_column('journal', sa.Column('chapter_interval', en, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('journal', 'chapter_interval',
               existing_type=sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='intervaltype'),
               type_=postgresql.INTERVAL(),
               existing_nullable=True)
    op.drop_column('journal', 'chapter_interval'),
    op.add_column('journal', sa.Column('chapter_interval', en, nullable=True))
    en.drop(op.get_bind())
    # ### end Alembic commands ###
