"""make template related to user, content nullable

Revision ID: 760c7f61c259
Revises: c5ae51850724
Create Date: 2022-07-14 20:21:44.754510

"""
import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa
import tradealpha
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '760c7f61c259'
down_revision = 'c5ae51850724'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template', sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False))
    op.alter_column('template', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.create_foreign_key(None, 'template', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'template', type_='foreignkey')
    op.alter_column('template', 'content',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('template', 'user_id')
    # ### end Alembic commands ###
