"""cascade on event owner_id

Revision ID: 7636e2a2b265
Revises: 5bfb9e506ab1
Create Date: 2022-08-20 09:42:58.250285

"""
from alembic import op
import sqlalchemy as sa
import tradealpha


# revision identifiers, used by Alembic.
revision = '7636e2a2b265'
down_revision = '5bfb9e506ab1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('event_owner_id_fkey', 'event', type_='foreignkey')
    op.create_foreign_key(None, 'event', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event', type_='foreignkey')
    op.create_foreign_key('event_owner_id_fkey', 'event', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###
