"""add sandbox col

Revision ID: 77577310b6d6
Revises: 26ad98d52e0c
Create Date: 2022-08-09 15:02:20.766339

"""
from alembic import op
import sqlalchemy as sa
import tradealpha


# revision identifiers, used by Alembic.
revision = '77577310b6d6'
down_revision = '26ad98d52e0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('sandbox', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('client', 'sandbox')
    # ### end Alembic commands ###
