"""trade doc

Revision ID: 78f5d22e6fe3
Revises: 39779de1e471
Create Date: 2022-09-11 14:07:26.669811

"""
from alembic import op
import sqlalchemy as sa
import tradealpha
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78f5d22e6fe3'
down_revision = '39779de1e471'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('journal', 'chapter_interval',
               existing_type=postgresql.INTERVAL(),
               type_=sa.Enum('DAY', 'WEEK', 'MONTH', name='intervaltype'),
               existing_nullable=True)
    op.add_column('trade', sa.Column('notes', tradealpha.common.dbmodels.types.Document, nullable=True))
    op.drop_column('trade', 'memo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade', sa.Column('memo', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('trade', 'notes')
    op.alter_column('journal', 'chapter_interval',
               existing_type=sa.Enum('DAY', 'WEEK', 'MONTH', name='intervaltype'),
               type_=postgresql.INTERVAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
