"""add event rank

Revision ID: 79f5a5cac328
Revises: 3dfc3b839d8c
Create Date: 2022-08-29 21:34:33.153501

"""
from alembic import op
import sqlalchemy as sa
import tradealpha


# revision identifiers, used by Alembic.
revision = '79f5a5cac328'
down_revision = '3dfc3b839d8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventrank',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('client_id', 'event_id', 'time')
    )
    op.add_column('eventscore', sa.Column('last_rank_update', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'eventscore', 'eventrank', ['client_id', 'event_id', 'last_rank_update'], ['client_id', 'event_id', 'time'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'eventscore', type_='foreignkey')
    op.drop_column('eventscore', 'last_rank_update')
    op.drop_table('eventrank')
    # ### end Alembic commands ###
