"""add cascade to chapter-journal foreign const

Revision ID: 8167c1b6e6e3
Revises: 5ef7b6e93e52
Create Date: 2022-05-28 23:38:47.842942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8167c1b6e6e3'
down_revision = '5ef7b6e93e52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('balance_association_chapter_id_fkey', 'balance_association', type_='foreignkey')
    op.drop_constraint('balance_association_balance_id_fkey', 'balance_association', type_='foreignkey')
    op.create_foreign_key(None, 'balance_association', 'chapter', ['chapter_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'balance_association', 'balance', ['balance_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('chapter_journal_id_fkey', 'chapter', type_='foreignkey')
    op.create_foreign_key(None, 'chapter', 'journal', ['journal_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('journal_association_client_id_fkey', 'journal_association', type_='foreignkey')
    op.drop_constraint('journal_association_journal_id_fkey', 'journal_association', type_='foreignkey')
    op.create_foreign_key(None, 'journal_association', 'client', ['client_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'journal_association', 'journal', ['journal_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'journal_association', type_='foreignkey')
    op.drop_constraint(None, 'journal_association', type_='foreignkey')
    op.create_foreign_key('journal_association_journal_id_fkey', 'journal_association', 'journal', ['journal_id'], ['id'])
    op.create_foreign_key('journal_association_client_id_fkey', 'journal_association', 'client', ['client_id'], ['id'])
    op.drop_constraint(None, 'chapter', type_='foreignkey')
    op.create_foreign_key('chapter_journal_id_fkey', 'chapter', 'journal', ['journal_id'], ['id'])
    op.drop_constraint(None, 'balance_association', type_='foreignkey')
    op.drop_constraint(None, 'balance_association', type_='foreignkey')
    op.create_foreign_key('balance_association_balance_id_fkey', 'balance_association', 'balance', ['balance_id'], ['id'])
    op.create_foreign_key('balance_association_chapter_id_fkey', 'balance_association', 'chapter', ['chapter_id'], ['id'])
    # ### end Alembic commands ###
