"""change client-journal relation2

Revision ID: 81ab644f4596
Revises: eb6e3d4bdc04
Create Date: 2022-05-28 22:45:08.759722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81ab644f4596'
down_revision = 'eb6e3d4bdc04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balance_association',
    sa.Column('balance_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['balance_id'], ['balance.id'], ),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ),
    sa.PrimaryKeyConstraint('balance_id', 'chapter_id')
    )
    op.drop_constraint('chapter_end_balance_id_fkey', 'chapter', type_='foreignkey')
    op.drop_constraint('chapter_start_balance_id_fkey', 'chapter', type_='foreignkey')
    op.drop_column('chapter', 'end_balance_id')
    op.drop_column('chapter', 'start_balance_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('start_balance_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('chapter', sa.Column('end_balance_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('chapter_start_balance_id_fkey', 'chapter', 'balance', ['start_balance_id'], ['id'])
    op.create_foreign_key('chapter_end_balance_id_fkey', 'chapter', 'balance', ['end_balance_id'], ['id'])
    op.drop_table('balance_association')
    # ### end Alembic commands ###
