"""new client enums

Revision ID: 87bb80bdb64f
Revises: 01187333c9f2
Create Date: 2022-09-04 19:17:57.005996

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

import tradealpha


# revision identifiers, used by Alembic.
revision = '87bb80bdb64f'
down_revision = '01187333c9f2'
branch_labels = None
depends_on = None


type = ENUM('BASIC', 'FULL', name='clienttype')
state = ENUM('OK', 'ARCHIVED', 'INVALID', name='clientstate')


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    type.create(bind=op.get_bind())
    state.create(bind=op.get_bind())

    op.add_column('client', sa.Column('type', type, nullable=False))
    op.add_column('client', sa.Column('state', state, nullable=False))
    op.drop_column('client', 'archived')
    op.drop_column('client', 'invalid')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    type.drop(bind=op.get_bind())
    state.drop(bind=op.get_bind())

    op.add_column('client', sa.Column('invalid', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('client', sa.Column('archived', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('client', 'state')
    op.drop_column('client', 'type')
    # ### end Alembic commands ###
