"""cascade pnldata.trade_id

Revision ID: 8aab3af36e9b
Revises: cf8fcdfc878c
Create Date: 2022-05-16 19:21:10.509061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aab3af36e9b'
down_revision = 'cf8fcdfc878c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('pnldata_trade_id_fkey', 'pnldata', type_='foreignkey')
    op.create_foreign_key(None, 'pnldata', 'trade', ['trade_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pnldata', type_='foreignkey')
    op.create_foreign_key('pnldata_trade_id_fkey', 'pnldata', 'trade', ['trade_id'], ['id'])
    # ### end Alembic commands ###
