"""stricter trade cols

Revision ID: 8ff5d4ba6008
Revises: 463e377fd137
Create Date: 2022-09-04 18:39:52.497110

"""
from alembic import op
import sqlalchemy as sa
import tradealpha


# revision identifiers, used by Alembic.
revision = '8ff5d4ba6008'
down_revision = '463e377fd137'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade', 'init_balance_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trade', 'max_pnl_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('trade', 'min_pnl_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('trade', 'min_pnl_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trade', 'max_pnl_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('trade', 'init_balance_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
