"""change uuid names

Revision ID: 941e4c044eb9
Revises: 
Create Date: 2022-04-25 17:59:25.206877

"""
import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '941e4c044eb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alert', 'side')
    op.add_column('alert', sa.Column('side', sa.Enum('BUY', 'SELL', name='side')))
    op.add_column('guild', sa.Column('avatar', sa.String(), nullable=True))
    op.alter_column('alert', column_name='user_uuid', new_column_name='user_id')
    op.alter_column('client', column_name='user_uuid', new_column_name='user_id')
    op.alter_column('label', column_name='user_uuid', new_column_name='user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert', new_colum_name='user_uuid', column_name='user_id')
    op.alter_column('client', new_colum_name='user_uuid', column_name='user_id')
    op.alter_column('label', new_colum_name='user_uuid', column_name='user_id')
    op.drop_column('guild', 'avatar')
    op.alter_column('alert', 'side',
                    existing_type=sa.Enum('BUY', 'SELL', name='side'),
                    type_=sa.VARCHAR(),
                    existing_nullable=True)
    # ### end Alembic commands ###
