"""add total_commision column to trade

Revision ID: 95727bb7bd57
Revises: e460c0f3c4a7
Create Date: 2022-05-22 20:14:36.932362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95727bb7bd57'
down_revision = 'e460c0f3c4a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade', sa.Column('total_commisions', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade', 'total_commisions')
    # ### end Alembic commands ###
