"""add created and updated at properties

Revision ID: 9f0fb5d60a18
Revises: 31268f1f9942
Create Date: 2022-08-14 15:45:41.236708

"""
from alembic import op
import sqlalchemy as sa
import tradealpha
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f0fb5d60a18'
down_revision = '31268f1f9942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chapter', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('chapter', sa.Column('last_edited', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('chapter', column_name='content', new_column_name='doc')
    op.add_column('client', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('client', sa.Column('last_edited', sa.DateTime(timezone=True), nullable=True))
    op.add_column('template', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('template', sa.Column('last_edited', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('template', column_name='content', new_column_name='doc')
    op.add_column('user', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user', sa.Column('last_edited', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_edited')
    op.drop_column('user', 'created_at')
    op.alter_column('chapter', new_column_name='content', column_name='doc')
    op.drop_column('template', 'last_edited')
    op.drop_column('template', 'created_at')
    op.drop_column('client', 'last_edited')
    op.drop_column('client', 'created_at')
    op.alter_column('template', new_column_name='content', column_name='doc')
    op.drop_column('chapter', 'last_edited')
    op.drop_column('chapter', 'created_at')
    # ### end Alembic commands ###
