"""add currency and rekt treshhold to event

Revision ID: a2e192a59a90
Revises: ee554b210b7b
Create Date: 2022-09-24 17:35:29.206199

"""
from alembic import op
import sqlalchemy as sa
import tradealpha
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2e192a59a90'
down_revision = 'ee554b210b7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('currency', sa.String(length=10), server_default='USD', nullable=False))
    op.add_column('event', sa.Column('rekt_treshhold', sa.Numeric(), server_default='-99', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'rekt_treshhold')
    op.drop_column('event', 'currency')
    # ### end Alembic commands ###
