"""add action table

Revision ID: a82b277b06e3
Revises: ac4dc505dd4d
Create Date: 2022-09-08 13:58:32.012301

"""
import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa
import tradealpha
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a82b277b06e3'
down_revision = 'ac4dc505dd4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('action',
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_edited', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('namespace', sa.String(length=12), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('trigger_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('action_type', sa.Enum('WEBHOOK', 'DISCORD', name='actiontype'), nullable=False),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('action')
    # ### end Alembic commands ###
