"""Rename discorduser col

Revision ID: af850a757dc4
Revises: 42e034613d08
Create Date: 2022-04-29 22:47:11.943240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af850a757dc4'
down_revision = '42e034613d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guild_association', column_name='discorduser_id', new_column_name='discord_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guild_association', new_colum_name='discorduser_id', column_name='discord_user_id')
    # ### end Alembic commands ###
