"""advanced currency cols

Revision ID: becc5951bf45
Revises: 3227580df717
Create Date: 2022-06-25 14:33:14.742843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import update
from sqlalchemy.orm import Session

from balancebot.common.dbsync import Base
from balancebot.common.dbmodels.trade import Trade

revision = 'becc5951bf45'
down_revision = '3227580df717'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade', sa.Column('settle', sa.String(length=5), nullable=True))
    op.add_column('trade', sa.Column('inverse', sa.Boolean(), nullable=True))

    db = Session(op.get_bind())
    db.execute(
        update(Trade).values(
            settle='USD',
            inverse=False
        )
    )
    db.commit()

    op.alter_column('trade', 'settle', nullable=False)
    op.alter_column('trade', 'inverse', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade', 'inverse')
    op.drop_column('trade', 'settle')
    # ### end Alembic commands ###
