"""migrate chpater interval enum

Revision ID: bf0c03abe6f9
Revises: 6f7d06d8ab2f
Create Date: 2022-09-09 14:34:13.586092

"""
from alembic import op
import sqlalchemy as sa
import tradealpha
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf0c03abe6f9'
down_revision = '6f7d06d8ab2f'
branch_labels = None
depends_on = None

en = sa.Enum('DAY', 'WEEK', 'MONTH', name='intervaltype')

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal', 'chapter_interval'),
    en.drop(bind=op.get_bind())
    en.create(bind=op.get_bind())
    op.add_column('journal', sa.Column('chapter_interval', en, nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('journal', 'chapter_interval',
               existing_type=sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='intervaltype'),
               type_=postgresql.INTERVAL(),
               existing_nullable=True)
    op.drop_column('journal', 'chapter_interval'),
    op.add_column('journal', sa.Column('chapter_interval', en, nullable=True))
    en.drop(op.get_bind())
    # ### end Alembic commands ###