"""add sync state to client

Revision ID: c3f7227d9a36
Revises: 18858522990e
Create Date: 2022-09-19 19:29:31.385005

"""
from alembic import op
import sqlalchemy as sa
import tradealpha
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c3f7227d9a36'
down_revision = '18858522990e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE clientstate ADD VALUE 'SYNCHRONIZING'")
    op.add_column('amount', sa.Column('total_transfered', sa.Numeric(), nullable=False))
    op.alter_column('journal', 'chapter_interval',
               existing_type=postgresql.INTERVAL(),
               type_=sa.Enum('DAY', 'WEEK', 'MONTH', name='intervaltype'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('journal', 'chapter_interval',
               existing_type=sa.Enum('DAY', 'WEEK', 'MONTH', name='intervaltype'),
               type_=postgresql.INTERVAL(),
               existing_nullable=True)
    op.drop_column('amount', 'total_transfered')
    # ### end Alembic commands ###
