"""add open_time to trade and new assoc tables

Revision ID: c96ad86e6564
Revises: 8167c1b6e6e3
Create Date: 2022-05-31 20:12:42.866682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import orm

revision = 'c96ad86e6564'
down_revision = '8167c1b6e6e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    session = orm.Session(bind=op.get_bind())

    op.create_table('chapter_trade_association',
    sa.Column('trade_id', sa.Integer(), nullable=False),
    sa.Column('chapter_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chapter_id'], ['chapter.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trade_id'], ['trade.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trade_id', 'chapter_id')
    )
    op.add_column('trade', sa.Column('open_time', sa.DateTime(timezone=True), nullable=True))

    from balancebot.common.dbmodels import TradeDB
    for trade in session.query(TradeDB).options(orm.selectinload(TradeDB.initial)):
        trade.open_time = trade.initial.time
    session.commit()

    op.alter_column('trade', column_name='open_time', nullable=False)



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade', 'open_time')
    op.drop_table('chapter_trade_association')
    # ### end Alembic commands ###
