"""New fields

Revision ID: cafb0a70bced
Revises: ccb574fad827
Create Date: 2022-05-07 11:42:54.922274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cafb0a70bced'
down_revision = 'ccb574fad827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_balance_time'), 'balance', ['time'], unique=False)
    op.drop_constraint('client_currently_realized_id_fkey', 'client', type_='foreignkey')
    op.create_foreign_key(None, 'client', 'realizedbalance', ['currently_realized_id'], ['id'], ondelete='SET NULL')
    op.add_column('execution', sa.Column('transfer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'execution', 'transfer', ['transfer_id'], ['id'])
    op.create_index(op.f('ix_pnldata_time'), 'pnldata', ['time'], unique=False)
    op.add_column('realizedbalance', sa.Column('client_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_realizedbalance_time'), 'realizedbalance', ['time'], unique=False)
    op.create_foreign_key(None, 'realizedbalance', 'client', ['client_id'], ['id'])
    op.add_column('trade', sa.Column('order_count', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transfer_time'), 'transfer', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transfer_time'), table_name='transfer')
    op.drop_column('trade', 'order_count')
    op.drop_constraint(None, 'realizedbalance', type_='foreignkey')
    op.drop_index(op.f('ix_realizedbalance_time'), table_name='realizedbalance')
    op.drop_column('realizedbalance', 'client_id')
    op.drop_index(op.f('ix_pnldata_time'), table_name='pnldata')
    op.drop_constraint(None, 'execution', type_='foreignkey')
    op.drop_column('execution', 'transfer_id')
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.create_foreign_key('client_currently_realized_id_fkey', 'client', 'balance', ['currently_realized_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_balance_time'), table_name='balance')
    # ### end Alembic commands ###
