"""remove global client on dc user

Revision ID: ccb574fad827
Revises: 6702ad72532d
Create Date: 2022-05-04 15:47:59.701787

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccb574fad827'
down_revision = '6702ad72532d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('discorduser_global_client_id_fkey', 'discorduser', type_='foreignkey')
    op.drop_column('discorduser', 'global_client_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('discorduser', sa.Column('global_client_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('discorduser_global_client_id_fkey', 'discorduser', 'client', ['global_client_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
