"""add commission col to execution

Revision ID: cf325bf06505
Revises: af850a757dc4
Create Date: 2022-04-30 18:55:52.526994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf325bf06505'
down_revision = 'af850a757dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution', sa.Column('commission', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execution', 'commission')
    # ### end Alembic commands ###
