"""differnetiate rpnl and upnl on pnldata

Revision ID: cf8fcdfc878c
Revises: ffd025c8849a
Create Date: 2022-05-15 22:21:45.311863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf8fcdfc878c'
down_revision = 'ffd025c8849a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pnldata', sa.Column('realized', sa.Numeric(), nullable=False))
    op.add_column('pnldata', sa.Column('unrealized', sa.Numeric(), nullable=False))
    op.drop_column('pnldata', 'amount')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pnldata', sa.Column('amount', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.drop_column('pnldata', 'unrealized')
    op.drop_column('pnldata', 'realized')
    # ### end Alembic commands ###
