"""extended currency info on exec

Revision ID: d03e280b54ba
Revises: 77b5f05a3fcf
Create Date: 2022-06-25 15:05:39.641905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import update
from sqlalchemy.orm import Session

from balancebot.common.dbmodels.execution import Execution

revision = 'd03e280b54ba'
down_revision = '77b5f05a3fcf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution', sa.Column('settle', sa.String(length=5), nullable=False))
    op.add_column('execution', sa.Column('inverse', sa.Boolean(), nullable=False))

    db = Session(op.get_bind())
    db.execute(
        update(Execution).values(
            settle='USD',
            inverse=False
        )
    )
    db.commit()

    op.alter_column('execution', 'settle', nullable=False)
    op.alter_column('execution', 'inverse', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execution', 'inverse')
    op.drop_column('execution', 'settle')
    # ### end Alembic commands ###
