"""rename transfer.fee to commission

Revision ID: d34d5d512aff
Revises: 87a393c2b228
Create Date: 2022-06-21 18:32:26.310175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd34d5d512aff'
down_revision = '87a393c2b228'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfer', column_name='fee', new_column_name='commission')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfer', new_column_name='fee', column_name='commission')
    # ### end Alembic commands ###
