"""add rpnl column to execution

Revision ID: d82f0fadb2dc
Revises: cf325bf06505
Create Date: 2022-05-02 20:23:24.038194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd82f0fadb2dc'
down_revision = 'cf325bf06505'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution', sa.Column('realized_pnl', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execution', 'realized_pnl')
    # ### end Alembic commands ###
