"""migrate to numeric from float v2

Revision ID: d8c03a699bb7
Revises: 18f3c3aa07fd
Create Date: 2022-05-15 14:15:53.821514

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd8c03a699bb7'
down_revision = '18f3c3aa07fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert', 'price',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               type_=sa.Numeric(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alert', 'price',
               existing_type=sa.Numeric(),
               type_=postgresql.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    # ### end Alembic commands ###
