"""add template table

Revision ID: e22aec034d40
Revises: 188a5325bac1
Create Date: 2022-07-05 19:05:50.453601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e22aec034d40'
down_revision = '188a5325bac1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal', sa.Column('default_template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'journal', 'template', ['default_template_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'journal', type_='foreignkey')
    op.drop_column('journal', 'default_template_id')
    # ### end Alembic commands ###
