"""change event description to be a document

Revision ID: e35c088672d2
Revises: 22a897d6961f
Create Date: 2022-08-22 00:02:38.985333

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text

import tradealpha


# revision identifiers, used by Alembic.
revision = 'e35c088672d2'
down_revision = '22a897d6961f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'description')
    op.add_column('event', sa.Column('description', tradealpha.common.dbmodels.types.Document(astext_type=Text())))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
