"""add journal

Revision ID: e460c0f3c4a7
Revises: fb4eb3a23a66
Create Date: 2022-05-22 12:13:17.702649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e460c0f3c4a7'
down_revision = 'fb4eb3a23a66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('chapter_interval', sa.Interval(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('start_balance_id', sa.Integer(), nullable=True),
    sa.Column('end_balance_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['end_balance_id'], ['balance.id'], ),
    sa.ForeignKeyConstraint(['journal_id'], ['journal.id'], ),
    sa.ForeignKeyConstraint(['start_balance_id'], ['balance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('daily')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('start_balance_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('end_balance_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], name='daily_client_id_fkey'),
    sa.ForeignKeyConstraint(['end_balance_id'], ['balance.id'], name='daily_end_balance_id_fkey'),
    sa.ForeignKeyConstraint(['start_balance_id'], ['balance.id'], name='daily_start_balance_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='daily_pkey'),
    sa.UniqueConstraint('date', name='daily_date_key')
    )
    op.drop_table('chapter')
    op.drop_table('journal')
    # ### end Alembic commands ###
