"""add trade template to client

Revision ID: eaf0901c43fd
Revises: d019cbe0748b
Create Date: 2022-10-04 21:04:51.801741

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa
from alembic import op
from sqlalchemy.orm import Session

from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'eaf0901c43fd'
down_revision = 'd019cbe0748b'
branch_labels = None
depends_on = None


def upgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('trade_template_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'client', 'template', ['trade_template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade():
    session = Session(bind=op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'client', type_='foreignkey')
    op.drop_column('client', 'trade_template_id')
    # ### end Alembic commands ###
