"""change client-journal relation

Revision ID: eb6e3d4bdc04
Revises: 681682d5a72c
Create Date: 2022-05-28 21:24:32.777706

"""
import fastapi_users_db_sqlalchemy
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb6e3d4bdc04'
down_revision = '681682d5a72c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_association',
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['client.id'], ),
    sa.ForeignKeyConstraint(['journal_id'], ['journal.id'], ),
    sa.PrimaryKeyConstraint('journal_id', 'client_id')
    )
    op.add_column('journal', sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False))
    op.drop_constraint('journal_client_id_fkey', 'journal', type_='foreignkey')
    op.create_foreign_key(None, 'journal', 'user', ['user_id'], ['id'])
    op.drop_column('journal', 'client_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal', sa.Column('client_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'journal', type_='foreignkey')
    op.create_foreign_key('journal_client_id_fkey', 'journal', 'client', ['client_id'], ['id'])
    op.drop_column('journal', 'user_id')
    op.drop_table('journal_association')
    # ### end Alembic commands ###
