"""journal to template many to one

Revision ID: ebfe0ff27301
Revises: 44c089be861c
Create Date: 2022-07-16 10:49:07.946967

"""
from alembic import op
import sqlalchemy as sa
import tradealpha


# revision identifiers, used by Alembic.
revision = 'ebfe0ff27301'
down_revision = '44c089be861c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('journal_template_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_template_association',
    sa.Column('journal_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('template_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journal.id'], name='journal_template_association_journal_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['template_id'], ['template.id'], name='journal_template_association_template_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('journal_id', 'template_id', name='journal_template_association_pkey')
    )
    # ### end Alembic commands ###
