"""remove total_transferred

Revision ID: ee554b210b7b
Revises: c3f7227d9a36
Create Date: 2022-09-20 19:42:30.942764

"""
from alembic import op
import sqlalchemy as sa
import tradealpha
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee554b210b7b'
down_revision = 'c3f7227d9a36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('amount', 'total_transfered')
    op.drop_column('balance', 'total_transfered')
    op.add_column('event', sa.Column('allow_transfers', sa.Boolean(), nullable=True))
    op.alter_column('journal', 'chapter_interval',
               existing_type=postgresql.INTERVAL(),
               type_=sa.Enum('DAY', 'WEEK', 'MONTH', name='intervaltype'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('journal', 'chapter_interval',
               existing_type=sa.Enum('DAY', 'WEEK', 'MONTH', name='intervaltype'),
               type_=postgresql.INTERVAL(),
               existing_nullable=True)
    op.drop_column('event', 'allow_transfers')
    op.add_column('balance', sa.Column('total_transfered', sa.NUMERIC(), autoincrement=False, nullable=False))
    op.add_column('amount', sa.Column('total_transfered', sa.NUMERIC(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
