"""add transfers table, make error non-persistent

Revision ID: eeec27da77ac
Revises: 941e4c044eb9
Create Date: 2022-04-26 20:26:51.141221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eeec27da77ac'
down_revision = '941e4c044eb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance', sa.Column('transfer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'balance', 'transfer', ['transfer_id'], ['id'], ondelete='SET NULL')
    op.drop_column('balance', 'error')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance', sa.Column('error', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'balance', type_='foreignkey')
    op.drop_column('balance', 'transfer_id')
    # ### end Alembic commands ###
