"""add extra journal options

Revision ID: f09c0b5bb30d
Revises: c96ad86e6564
Create Date: 2022-06-01 18:39:51.103706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f09c0b5bb30d'
down_revision = 'c96ad86e6564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journal', sa.Column('auto_generate', sa.Boolean(), nullable=True))
    op.add_column('journal', sa.Column('track_performance', sa.Boolean(), nullable=True))
    op.add_column('journal', sa.Column('type', sa.Enum('MANUAL', 'CLIENTS', name='journaltype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journal', 'type')
    op.drop_column('journal', 'track_performance')
    op.drop_column('journal', 'auto_generate')
    # ### end Alembic commands ###
