"""add new trade columns

Revision ID: f28d75c7d765
Revises: 2197236c87bb
Create Date: 2022-05-15 11:22:51.205888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.dialects.postgresql import ENUM

from balancebot.common.enums import ExecType

revision = 'f28d75c7d765'
down_revision = '2197236c87bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    enum = ENUM('TRADE', 'STOP', 'TP', 'TRANSFER', name='exectype')
    enum.create(op.get_bind(), checkfirst=False)
    op.drop_column('execution', 'type')
    op.add_column(
        'execution',
        sa.Column(
            'type', sa.Enum('TRADE', 'STOP', 'TP', 'TRANSFER', name='exectype'), nullable=True
        )
    )

    op.drop_constraint('execution_transfer_id_fkey', 'execution', type_='foreignkey')
    op.drop_column('execution', 'transfer_id')
    op.add_column('trade', sa.Column('transferred_qty', sa.Float(), nullable=True))
    op.add_column('trade', sa.Column('tp', sa.Float(), nullable=True))
    op.add_column('trade', sa.Column('sl', sa.Float(), nullable=True))
    op.add_column('transfer', sa.Column('execution_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transfer', 'execution', ['execution_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    ENUM(name='exectype').drop(op.get_bind(), checkfirst=False)
    op.drop_column('execution', 'type')
    op.add_column('execution', sa.Column('type', sa.VARCHAR(), nullable=True))
    op.drop_constraint(None, 'transfer', type_='foreignkey')
    op.drop_column('transfer', 'execution_id')
    op.drop_column('trade', 'sl')
    op.drop_column('trade', 'tp')
    op.drop_column('trade', 'transferred_qty')
    op.add_column('execution', sa.Column('transfer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('execution_transfer_id_fkey', 'execution', 'transfer', ['transfer_id'], ['id'])
    op.alter_column('execution', 'type',
               existing_type=sa.Enum('TRADE', 'STOP', 'TP', 'TRANSFER', name='exectype'),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
