"""cascade deletion for chapter

Revision ID: f784a913492c
Revises: e3b3306173d5
Create Date: 2022-07-15 16:21:01.383877

"""
from alembic import op
import sqlalchemy as sa
import tradealpha


# revision identifiers, used by Alembic.
revision = 'f784a913492c'
down_revision = 'e3b3306173d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('chapter_parent_id_fkey', 'chapter', type_='foreignkey')
    op.create_foreign_key(None, 'chapter', 'chapter', ['parent_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chapter', type_='foreignkey')
    op.create_foreign_key('chapter_parent_id_fkey', 'chapter', 'chapter', ['parent_id'], ['id'])
    # ### end Alembic commands ###
