"""add transfered col to balance

Revision ID: fb4eb3a23a66
Revises: d1630e1fc83f
Create Date: 2022-05-19 21:32:04.704242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb4eb3a23a66'
down_revision = 'd1630e1fc83f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
