"""change execution side to enum

Revision ID: ffd025c8849a
Revises: 559b4d802b81
Create Date: 2022-05-15 21:22:31.989720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy.dialects.postgresql import ENUM

revision = 'ffd025c8849a'
down_revision = '559b4d802b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execution', 'side')
    op.add_column('execution', sa.Column('side', sa.Enum('BUY', 'SELL', name='side'), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('execution', 'side')
    op.add_column('execution', sa.Column('side', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
